"""MinHeap using Python's built-in heapq module.

Scenario: Tracking spacecraft arrivals and departures from a space station radar.
You observe a sequence of license numbers and need to efficiently track all spacecraft
and remove the spacecraft with the smallest license number.

Using heapq, Python maintains the min-heap property automatically:
  - heapq.heappush(heap, item): Insert in O(log n)
  - heapq.heappop(heap):        Remove and return the minimum in O(log n)
  - heap[0]:                    Peek at the minimum in O(1)

Time complexity:
    - insert: O(log n) per element
    - delete_min: O(log n)
Space complexity: O(n)
"""

import heapq


class Solution:
    """Implement MinHeap using Python's heapq."""

    def __init__(self):
        """Initialize empty heap."""
        self.minHeap = []

    def insert(self, elt):
        """Insert element into heap, maintaining min-heap property."""
        heapq.heappush(self.minHeap, elt)

    def delete_min(self):
        """Remove and return the minimum element."""
        if not self.minHeap:
            return None
        return heapq.heappop(self.minHeap)

    def min_element(self):
        """Return the minimum element without removing it."""
        if not self.minHeap:
            return None
        return self.minHeap[0]

    def size(self):
        """Return the number of elements in the heap."""
        return len(self.minHeap)


# ── Demo ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    # Create an empty MinHeap instance
    heap = Solution()

    # Random numbers generated by a hypothetic radar for a real-world simulation
    randomNumbers = [23, 42, 14, 30, 27, 56, 14, 9, 5, 21, 34]

    # Inserting the generated random numbers into the MinHeap
    print("Inserting randomly generated license numbers into MinHeap.")
    for number in randomNumbers:
        heap.insert(number)
    print(f"Min Heap after inserting random numbers: {heap.minHeap}\n")

    # Removing the smallest numbers from the MinHeap for a real-world simulation
    for i in range(15):
        minNumber = heap.delete_min()
        if minNumber is None:
            print("Min Heap is empty. No numbers to delete.")
        else:
            print(
                f"Min Heap after removing the smallest number {minNumber}: {heap.minHeap}"
            )
